### PR TITLE
fix: Basic authentication configuration at the branch level

### PR DESCRIPTION
**Pull request by sestrella**
## what

Module consumers cannot pass a custom `basic_auth_credentials` per branch using the existing variables. At the branch level, there is also a typo on `enable_basic_auth`.

## why

The changes made in this PR allow consumers to configure different basic authentication credentials for each branch.

### CODE REVIEW

**Review by sadjow — APPROVED** [review]
LGTM

**Comment by skilef** [comment]
Please review this, it would be really helpful!

**Comment by kevcube** [comment]
@sestrella can you please update base branch and I will look to get this merged

**Comment by kevcube** [comment]
@sestrella tests failing and readme is out of date, can you locally run `make init; make readme` (on macOS `brew install make; gmake init; gmake readme`)

**Comment by sestrella** [comment]
@kevcube done. Would you mind taking a second look, please?

**Comment by kevcube** [comment]
@sestrella tests are still failing. It doesn't appear to be related to your PR but if you have time to investigate that would be appreciated. Otherwise I'll check it out when I'm able to.

**Comment by sestrella** [comment]
@kevcube After taking a closer look at the job log, I found the following relevant information:

```
TestExamplesComplete 2023-12-29T06:54:08Z logger.go:66: │ Error: creating Amplify App (eg-ue2-test-amplify-jrjxrn): BadRequestException: There was an issue setting up your repository. Please try again later.({"message":"Moved Permanently","url":"https://api.github.com/repositories/498423879/hooks","documentation_url":"https://docs.github.com/rest/guides/best-practices-for-using-the-rest-api#follow-redirects"})
TestExamplesComplete 2023-12-29T06:54:08Z logger.go:66: │ 
TestExamplesComplete 2023-12-29T06:54:08Z logger.go:66: │   with module.amplify_app.aws_amplify_app.default[0],
TestExamplesComplete 2023-12-29T06:54:08Z logger.go:66: │   on ../../main.tf line 10, in resource "aws_amplify_app" "default":
TestExamplesComplete 2023-12-29T06:54:08Z logger.go:66: │   10: resource "aws_amplify_app" "default" {
TestExamplesComplete 2023-12-29T06:54:08Z logger.go:66: │ 
TestExamplesComplete 2023-12-29T06:54:08Z logger.go:66: ╵
TestExamplesComplete 2023-12-29T06:54:08Z retry.go:99: Returning due to fatal error: FatalError{Underlying: error while running command: exit status 1; ╷
│ Error: creating Amplify App (eg-ue2-test-amplify-jrjxrn): BadRequestException: There was an issue setting up your repository. Please try again later.({"message":"Moved Permanently","url":"https://api.github.com/repositories/498423879/hooks","documentation_url":"https://docs.github.com/rest/guides/best-practices-for-using-the-rest-api#follow-redirects"})
```

I'm wondering if this is related to the fact that the [amplify-test2](https://github.com/cloudposse-archives/amplify-test2) appears to be transferred from the [cloudposse](https://github.com/cloudposse) organization to the [cloudposse-archives](https://github.com/cloudposse-archives) organization. I submitted a commit updating the URL for the repository found in the complete example.

**Comment by sestrella** [comment]
@kevcube I got a different error this time. Perhaps is related to the permissions associated with the GH token?

```
TestExamplesComplete 2024-01-03T03:18:06Z logger.go:66: │ Error: creating Amplify App (eg-ue2-test-amplify-t9vp6d): BadRequestException: There was an issue setting up your repository. Please try again later.({"message":"Not Found","documentation_url":"https://docs.github.com/rest/repos/webhooks#create-a-repository-webhook"})
TestExamplesComplete 2024-01-03T03:18:06Z logger.go:66: │ 
TestExamplesComplete 2024-01-03T03:18:06Z logger.go:66: │   with module.amplify_app.aws_amplify_app.default[0],
TestExamplesComplete 2024-01-03T03:18:06Z logger.go:66: │   on ../../main.tf line 10, in resource "aws_amplify_app" "default":
TestExamplesComplete 2024-01-03T03:18:06Z logger.go:66: │   10: resource "aws_amplify_app" "default" {
TestExamplesComplete 2024-01-03T03:18:06Z logger.go:66: │ 
TestExamplesComplete 2024-01-03T03:18:06Z logger.go:66: ╵
TestExamplesComplete 2024-01-03T03:18:06Z retry.go:99: Returning due to fatal error: FatalError{Underlying: error while running command: exit status 1; ╷
│ Error: creating Amplify App (eg-ue2-test-amplify-t9vp6d): BadRequestException: There was an issue setting up your repository. Please try again later.({"message":"Not Found","documentation_url":"https://docs.github.com/rest/repos/webhooks#create-a-repository-webhook"})
│ 
│   with module.amplify_app.aws_amplify_app.default[0],
│   on ../../main.tf line 10, in resource "aws_amplify_app" "default":
│   10: resource "aws_amplify_app" "default" {
│ 
╵}
```

**Comment by kevcube** [comment]
@sestrella not sure how to proceed with that one. for a shorter debug loop you can try just `terraform apply`-ing the `examples/complete` into your own AWS and GitHub accounts until you find a working solution. I'm not an admin in Cloudposse so if it's a token issue I can call in someone else.

**Comment by sestrella** [comment]
@kevcube I finally made it back to this PR. I made it work by creating a fork of https://github.com/cloudposse-archives/amplify-test2 to which I had write access; the following GH token permissions were required to make the `complete/example` work:

image

On a side note, according to the official documentation, a token with write access is required to set up a webhook, so my guess is that the token used by the CI lacks the necessary permissions:

image

Reference: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/amplify_app#access_token

**Comment by sestrella** [comment]
Hi @kevcube, I'm wondering if there is anything else I can do on my end to help get this PR move forward. Please let me know.

**Comment by sestrella** [comment]
@kevcube Thank you for triggering the CI again. I realized the check for the README was failing, so I re-ran `gmake init; gmake readme`.

**Comment by sestrella** [comment]
I look closely at the [error message](https://github.com/cloudposse/actions/actions/runs/8142118885/job/22250947823#step:9:476):

> BadRequestException: There was an issue setting up your repository. Please try again later

However, it appears to be a little misleading because the GH status page has not revealed any recent issues. Based on my tests a few weeks ago, I continue to believe this is related to token permissions. I'm wondering if the token was revisited.

**Comment by kevcube** [comment]
@sestrella the repo has been moved from cloudposse-archives back to cloudposse, can you please update the reference in this PR and we will try tests again

**Comment by sestrella** [comment]
@kevcube done! Let's see how it goes 🤞🏼

**Comment by fm7-1** [comment]
Hello, @kevcube. I tested this PR by applying the Terraform code in "examples/complete" and was able to use it with our AWS and GH accounts. 

image

I also ran the tests, and they work as expected. For this, I created a personal GitHub token with the permissions mentioned by @sestrella in a previous comment and forked the [amplify-test2](https://github.com/cloudposse/amplify-test2) repository. After changing the repository URL in the test fixtures to my fork, the tests passed. 

image

Please let me know if I can provide additional information that will allow us to move forward with this PR.

**Comment by fm7-1** [comment]
@hans-d - Perhaps the token used for testing is missing the public_repo permission?

image

**Comment by hans-d** [comment]
@fm7-1 could be.We need to check various options re this.

**Comment by sestrella** [comment]
@goruha `terratest` appears to be failing for the same reasons that it fails on #32. Here are the links to the runs: 

- [This PR](https://github.com/cloudposse/actions/actions/runs/8928200384)
- [PR #32](https://github.com/cloudposse/actions/actions/runs/8892097264/job/24415455260)

image

**Comment by fm7-1** [comment]
Hello, @goruha. I have rebased this PR with the latest commits in `main`. Could you run the tests again, please?

**Comment by fm7-1** [comment]
Hello, everyone! I see `terratest` is still failing with the same error as before. Is there anyway we can assist to move forward with the fix?

**Comment by osterman** [comment]
The hold up is we finally had switched/deprecated all our workflows in hundreds of repos from using PATs, but now this one repo needs a PAT. The terraform provider for amplify doesn't work with fine grained tokens. As a result we need to do a one off for this repo. We are still working on it, but it's in between other work.

**Comment by fm7-1** [comment]
Got it! Thank you for your prompt response, @osterman!

**Comment by goruha** [comment]
@sestrella can you pls update branch or rebase?

**Comment by fm7-1** [comment]
@goruha Done, I have rebased this branch

**Review by goruha — APPROVED** [review]

**Pull request merged**
