### PR TITLE
feat: allow attachment of managed amplify admin policy

### PR DESCRIPTION
**Pull request by kevcube**
## what

AWS provides a managed policy for AWS Amplify roles
This PR gives a boolean flag to allow users to attach this policy

## why

It's a prewritten, AWS-approved policy. Useful to Amplify users.

## references

https://us-east-1.console.aws.amazon.com/iam/home?region=us-east-1#/policies/details/arn%3Aaws%3Aiam%3A%3Aaws%3Apolicy%2FAdministratorAccess-Amplify

### CODE REVIEW

**Review by goruha — CHANGES_REQUESTED** [review]
@kevcube I think if would be better to have variable `managed_policy_arns ` as list of policy arns to attach instead of bool variable that attaches only one hardcoded policy

**Comment by osterman** [comment]
I agree with @goruha

**Pull request closed without merging**
